Repository typicalbot/typicalbot-deno, pull requests merged in 2021-06, with the labels that each got.

#6 feat: add proxy ws
  config.ts
  deps.ts
  mod.ts
  src/events/interactionCreate.ts
  src/gateway/mod.ts
Labels: type: feat

#11 feat: add dotenv
  .env.example
  .gitignore
  src/config.ts
Labels: type: feat

#10 chore: remove vscode config and gitignore it
  .gitignore
  .vscode/settings.json
Labels: type: chore

#15 refactor: use command name for registry
  src/rest/cache.ts
  src/rest/commands/animal/animal.ts
  src/rest/commands/animal/animalfact.ts
  src/rest/commands/fun/advice.ts
  src/rest/commands/fun/chucknorris.ts
  src/rest/commands/fun/coinflip.ts
  src/rest/commands/fun/dice.ts
  src/rest/commands/fun/meme.ts
  src/rest/commands/fun/pun.ts
  src/rest/commands/fun/thouart.ts
  src/rest/commands/fun/yearfact.ts
  src/rest/commands/fun/yomama.ts
  src/rest/commands/general/docs.ts
  src/rest/commands/general/invite.ts
  src/rest/commands/general/premium.ts
  src/rest/commands/information/ping.ts
  src/rest/commands/moderation/ban.ts
  src/rest/commands/moderation/kick.ts
  src/rest/commands/moderation/purge.ts
  src/rest/commands/moderation/say.ts
  src/rest/commands/system/debug.ts
  src/rest/common/command/CommandCollection.ts
Labels: type: refactor

#9 chore: update copyright and licensing notices
  README.md
  src/rest/common/util/i18next.ts
  src/rest/common/util/loader.ts
Labels: type: chore

#16 refactor: localize command descriptions (force en_US)
  src/rest/commands/animal/animal.ts
  src/rest/commands/animal/animalfact.ts
  src/rest/commands/fun/advice.ts
  src/rest/commands/fun/chucknorris.ts
  src/rest/commands/fun/coinflip.ts
  src/rest/commands/fun/dice.ts
  src/rest/commands/fun/meme.ts
  src/rest/commands/fun/pun.ts
  src/rest/commands/fun/thouart.ts
  src/rest/commands/fun/yearfact.ts
  src/rest/commands/fun/yomama.ts
  src/rest/commands/general/docs.ts
  src/rest/commands/general/invite.ts
  src/rest/commands/general/premium.ts
  src/rest/commands/information/ping.ts
  src/rest/commands/moderation/ban.ts
  src/rest/commands/moderation/kick.ts
  src/rest/commands/moderation/purge.ts
  src/rest/commands/moderation/say.ts
  src/rest/commands/system/debug.ts
  src/rest/common/util/i18next.ts
  src/rest/languages/en_US/commands/animal/animal.json
  src/rest/languages/en_US/commands/animal/animalfact.json
  src/rest/languages/en_US/commands/fun/advice.json
  src/rest/languages/en_US/commands/fun/chucknorris.json
  src/rest/languages/en_US/commands/fun/coinflip.json
  src/rest/languages/en_US/commands/fun/dice.json
  src/rest/languages/en_US/commands/fun/meme.json
  src/rest/languages/en_US/commands/fun/pun.json
  src/rest/languages/en_US/commands/fun/thouart.json
  src/rest/languages/en_US/commands/fun/yearfact.json
  src/rest/languages/en_US/commands/fun/yomama.json
  src/rest/languages/en_US/commands/general/docs.json
  src/rest/languages/en_US/commands/general/invite.json
  src/rest/languages/en_US/commands/general/premium.json
  src/rest/languages/en_US/commands/information/ping.json
  src/rest/languages/en_US/commands/moderation/ban.json
  src/rest/languages/en_US/commands/moderation/kick.json
  src/rest/languages/en_US/commands/moderation/purge.json
  src/rest/languages/en_US/commands/moderation/say.json
  src/rest/languages/en_US/commands/system/debug.json
  src/rest/mod.ts
Labels: type: refactor

#12 chore: codeowners file
  .github/CODEOWNERS
Labels: type: chore

#13 chore: security.md file
  .github/SECURITY.md
Labels: type: chore

#14 chore: update readme
  README.md
Labels: type: chore

#17 refactor: use application owner for debug command
  deps.ts
  src/rest/cache.ts
  src/rest/commands/system/debug.ts
  src/rest/mod.ts
Labels: type: refactor

#20 chore: configure .editorconfig
  .editorconfig
  gateway.Dockerfile
  rest.Dockerfile
Labels: type: chore
